export const constants = {
 SHOW_NOTE : "SHOW_NOTE",
 SHOW_CATEGORY : "SHOW_CATEGORY",
 HIDE_NOTE: "HIDE_NOTE",
 HIDE_CATEGORY : "HIDE_CATEGORY",
 ADD_NOTE : "ADD_NOTE",
 DEL_NOTE : "DEL_NOTE", 
 UPD_NOTE : "UPD_NOTE", 
 ADD_CAT : "ADD_CAT",
 DEL_CAT : "DEL_CAR",
 UPD_CAT : "UPD_CAT" 
}